spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://127.0.0.1/db2
    username: root
    password: Root1120@
#    driver-class-name: com.mysql.cj.jdbc.Driver

# jdbcTemplate sql log
logging:
  level:
    org:
      springframework:
        jdbc: debug
    hello:
      itemservice:
        repository:
          mybatis: trace

# MyBatis
mybatis:
  type-aliases-package: hello.itemservice.domain # 하위 패키지 모두 생략 가능. 패키지 이름 충돌 등으로 세부적인 하위 패키지를 명시해두는 것 고려. 여러 디렉토리도 설정 가능. ,hello...식으로.
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/**/*.xml
