# Generated by Django 4.1 on 2022-08-24 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opening_position", models.CharField(max_length=50)),
                ("job_description", models.TextField()),
                ("required_skill", models.CharField(max_length=50)),
                ("contract_reward", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobplatform.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EndUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jobpost_set",
                    models.ManyToManyField(blank=True, to="jobplatform.jobpost"),
                ),
            ],
        ),
    ]
